services:
  smtp:
    image: inbucket/inbucket
    ports:
      - 1025:2500
      - 8025:9000

  db:
    image: postgres:12
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_MULTIPLE_DATABASES=codex,codex_shadow,codex_test
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./docker/postgres/multiple-databases.sh:/docker-entrypoint-initdb.d/multiple-databases.sh
    ports:
      - 5432:5432

  codex:
    profiles:
      - production
    build:
      dockerfile: ./Dockerfile
    depends_on:
      - smtp
      - db
    env_file:
      - .env
      - .env.local
    environment:
      - DATABASE_URL=postgres://postgres@db/codex
      - MAILER_DSN=smtp://smtp:1025
    ports:
      - 3000:3000

volumes:
  db_data:
