name: CI-CD

on:
  push:
    branches:
      - "main"
      - "releases/**"
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
  pull_request: ~

jobs:
  call-tests:
    uses: ./.github/workflows/tests.yaml
  call-e2e:
    needs: call-tests
    uses: ./.github/workflows/e2e.yaml
  call-image:
    needs: call-e2e
    uses: ./.github/workflows/image.yaml
